### ISSUE TITLE
ESP never works to me

### ISSUE THREAD

**Issue by kzashy** [sevenseassinbad/d3d11hook#3]
Why only my esp never Works ? Aimbot, chams, nospread, instant-reload... all things Works, except ESP, nothing is displayed() on my screen.

**Comment by Vastopian** [comment]
i recommend changing the hot key to a different key like VK_F7 and try using that. thats what i did i dont have side mouse buttons.

**Comment by kzashy** [comment]
solved, its a problem with another overlays (ex. msi afterburner)
