### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by HAlLRAKE** [sevenseassinbad/d3d11hook#8]
Injecting on startup with "mininject" crashes the game right after the launch. 
Using another injector, I could search the game, but immediately after dropping from bus, I received a permanent ban.
_Note: I do have Full screen mode ON._

**Comment by PavelNetesov** [comment]
Also got a ban

**Comment by sevenseassinbad** [comment]
There was a game patch with new anticheat measures. The hack has been updated and you can use it again.
